sudo: false

language: python

python:
    - 3.6
    - "3.7-dev"

before_install:
    # alias package
    - PACKAGE=`pwd`/abjadext

    # upgrade pip:
    - pip install --upgrade pip

    # install mypy:
    - pip install mypy

    # install lilypond:
    - LILYPOND=/tmp/lilypond
    - LILYPOND_URL=http://download.linuxaudio.org/lilypond/binaries/linux-64
    - LILYPOND_SOURCE=lilypond-2.19.80-1.linux-64.sh
    - wget -q -O $LILYPOND $LILYPOND_URL/$LILYPOND_SOURCE
    - sh $LILYPOND --batch

    # clone & install abjad dev branch:
    - ABJAD=/tmp/abjad
    - git clone -b trevor/dev https://github.com/Abjad/abjad.git $ABJAD
    - pip install -e $ABJAD
    - export MYPYPATH=$ABJAD
    - export PATH=$PATH:$ABJAD/abjad/scr

    # set path:
    #- export PATH=/home/travis/bin:$PATH

    #- pip install -U https://github.com/Abjad/abjad/archive/master.zip
    
    # install uqbar:
#    - pip install -U https://github.com/josiah-wolf-oberholtzer/uqbar/archive/master.zip
#    - pip install --no-deps --target /tmp/typehints https://github.com/josiah-wolf-oberholtzer/uqbar/archive/master.zip
#    - export MYPYPATH=$MYPYPATH:/tmp/typehints
    - UQBAR=/tmp/uqbar
    - pip install --no-deps --target $UQBAR 'uqbar>=0.2.13'
    - export MYPYPATH=$MYPYPATH:$UQBAR

    # log setup:
    - echo $MYPYPATH
    - echo $PATH
    - ls
    - ls /tmp
    - pwd
    - which mypy

install:
    - pip install coverage
    #- pip install -e .[test] # maybe don't need test dependencies
    - pip install -e .

script:
    - mypy $PACKAGE
    - `which py.test` -rf $PACKAGE

after_success:
    - pip install --quiet coveralls
    - coveralls
