os: linux

dist: xenial

language: python

python:
    - 3.6
    - 3.7
    - 3.8

env:
    global:
        - LILYPOND_URL=http://lilypond.org/downloads/binaries/linux-64/
        - LILYPOND_VERSION=2.19.84

before_install:

    # install pip, isort, flake8, mypy
    - pip install --upgrade pip
    - pip install flake8
    - pip install isort
    - pip install mypy

    - wget -q ${LILYPOND_URL}lilypond-${LILYPOND_VERSION}-1.linux-64.sh
    - sh lilypond-$LILYPOND_VERSION-1.linux-64.sh --batch
    - export PATH=/home/travis/bin:$PATH
    - pip install -U pip regex
    - export ABJAD_ARCHIVE=https://github.com/Abjad/abjad/archive/master.zip
    - pip install -U $ABJAD_ARCHIVE
    - pip install --no-deps --target /tmp/typehints $ABJAD_ARCHIVE
    - pip install --no-deps --target /tmp/typehints uqbar
    - export MYPYPATH=/tmp/typehints

    # log versions
    - black --version
    - flake8 --version
    - isort --version
    - mypy --version
    - pip --version
    # - pytest --version

    # log environment variables
    - echo $MYPYPATH
    - echo $PATH
    - echo $TRAVIS_BUILD_DIR

    # log script paths
    - which black-check
    - which flake8-check
    - which isort-check
    - which prime-parser-tables

    # log present working directory
    - pwd
    - ls

install:
    - pip install -e .[test]
    - pytest --version

script:
    - make black-check
    - make flake8
    - make isort-check
    - if [[ $TRAVIS_PYTHON_VERSION != 3.6 ]]; then mypy .; fi
    - make pytest

after_success:
    - pip install --quiet coveralls
    - coveralls
