name: abjad-ext-rmakers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install LilyPond
      run: |
        lilypond_url=http://lilypond.org/download/binaries/linux-64/
        lilypond_source=lilypond-2.23.0-1.linux-64.sh
        wget -q -O /tmp/lilypond $lilypond_url/$lilypond_source
        sh /tmp/lilypond --batch

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install Abjad
      run: |
        git clone -b trevor/dev https://github.com/Abjad/abjad.git /tmp/abjad
        pip install /tmp/abjad[dev]

    - name: Install this package
      run: |
        python -m pip install -e .

    - name: Log versions
      run: |
        # lilypond is installed in /home/runner/bin
        export PATH=/home/runner/bin:${PATH}
        black --version
        flake8 --version
        isort --version
        mypy --version
        pip --version
        pytest --version
        lilypond --version

    - name: Run checks and tests
      run: |
        # lilypond is installed in /home/runner/bin
        export PATH=/home/runner/bin:${PATH}
        export MYPYPATH=$MYPYPATH:/tmp/abjad
        echo $MYPYPATH
        make black-check
        make flake8
        make isort-check
        make mypy
        make pytest
